[theme]
primaryColor = "#f63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20
enableWebsocketCompression = false
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true
fastReruns = true

[deprecation]
showPyplotGlobalUse = false 